### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Grimovich/grid-template#1]
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/229886211-59c6ba18-6e94-418e-9ce7-a56e4abc23a0.png)

**Comment by Grimovich** [comment]
Ошибка исправлена  

![Screenshot_1](https://user-images.githubusercontent.com/125678372/229895182-3ffec1dc-390c-41ae-bc9d-9c35643edfb8.png)
